# AuxProtect
# Developed by Heliosares
# https://www.spigotmc.org/resources/auxprotect.99147/

# Set the language file to be used. 
# Default: en-us
# File location: lang/en-us.yml
lang: en-us

# MySQL functionality is EXPERIMENTAL. Use with caution.
# SQLITE LOGS WILL NOT BE MIGRATED.
MySQL:
  use: false # Recommended: false
  host: localhost
  port: 3306
  database: database
  username: username
  password: password
  # Prefix to be used for all table names. Editing this after creating your databases will cause all past data to be lost.
  # This only applied to MySQL, not SQLite
  table-prefix: ''

# Use this to force all commands within AuxProtect to override all other plugin's commands.
# You only need to enable this if another plugin is interfering. 
OverrideCommands: false

# Automatic purging
# This will be performed every time the plugin is loaded, up to once every 12 hours.
# Times are formatted the same as lookups. (e.g. 10w is 10 weeks)
# Set any table to "off" to disable.
# Set any table to "default" to use the 'default' setting.
# For a list of which actions belong to which tables, see https://github.com/Heliosares/AuxProtect/wiki/Actions
# Minimum: 2w
AutoPurge:
  Enabled: false
  default: 180d


# Note: This action list is mostly generated by the plugin at runtime. 
# Disabling an action here will remove the ability to look up that
# action as well as disable the logging of that action.
# It will not affect any data currently in the database.
Actions:
  money:
    Enabled: true
    Interval: 600000
  pos:
    Enabled: true
    Interval: 3000
  inventory:
    Enabled: true
    WorldChange: false
    Interval: 3600000
    # Enables differential logging and searching of inventories down to the second. 
    # This feature is experimental and will consume significantly more disk space.
    # Do not use this feature if your server is medium to large.
    Diff-Interval: 0
    # Use this if you run into issues with death inventories being empty. 
    # This is usually due to a plugin like DeathChests clearing the inventory before AuxProtect sees it.
    LowestPriority: false

# Automatically check for updates and display notifications in game.
# It's recommended to leave this enabled, as I'm constantly improving the plugin.
checkforupdates: true