# AuxProtect
# Developed by Heliosares
# https://www.spigotmc.org/resources/auxprotect.99147/

# MySQL functionality is EXPERIMENTAL. Use with caution.
# OLD LOGS WILL NOT BE MIGRATED.
MySQL:
  use: false # Recommended: false
  host: localhost
  port: 3306
  database: database
  username: username
  password: password
# Prefix to be used for all table names. Editing this after creating your databases will cause all past data to be lost.
  table-prefix: ''
# Use this to force all commands within auxprotect to override all other plugin's commands.
# You only need to enable this if another plugin is interfering. 
OverrideCommands: false
Actions:
  leash:
    Enabled: true
  session:
    Enabled: true
  kick:
    Enabled: true
  shop:
    Enabled: true
  bucket:
    Enabled: true
  mount:
    Enabled: true
  respawn:
    Enabled: true
  consume:
    Enabled: true
  recover:
    Enabled: true
  money:
    Enabled: true
    Interval: 600000
  pos:
    Enabled: true
    Interval: 3000
  hurt:
    Enabled: true
  inv:
    Enabled: true
  command:
    Enabled: true
  kill:
    Enabled: true
  land:
    Enabled: true
  ip:
    Enabled: true
  inventory:
    Enabled: true
    WorldChange: false
    Interval: 3600000
    # Enables differential logging and searching of inventories down to the second. 
    # This feature is experimental and will consume more disk space.
    Diff-Interval: 0
    # Use this if you run into issues with death inventories being empty. 
    # This is usually due to a plugin like DeathChests clearing the inventory before AuxProtect sees it.
    LowestPriority: false
  launch:
    Enabled: true
  grab:
    Enabled: true
  drop:
    Enabled: true
  pickup:
    Enabled: true
  itemframe:
    Enabled: true
  ahlist:
    Enabled: true
  ahbuy:
    Enabled: true
  elytra:
    Enabled: true
  gamemode:
    Enabled: true
  explode:
    Enabled: true
  auctionbuy:
    Enabled: true
  lightning:
    Enabled: true
  vein:
    Enabled: true
  pay:
    Enabled: true
  auctionlist:
    Enabled: true
  activity:
    Enabled: true
  alert:
    Enabled: true
  totem:
    Enabled: true
  jobs:
    Enabled: true
  tame:
    Enabled: true
  censor:
    Enabled: true
  breakitem:
    Enabled: true
  tp:
    Enabled: true
  towncreate:
    Enabled: true
  nationdelete:
    Enabled: true
  townyname:
    Enabled: true
  townrename:
    Enabled: true
  townjoin:
    Enabled: true
  nationrename:
    Enabled: true
  townmerge:
    Enabled: true
  nationjoin:
    Enabled: true
  townclaim:
    Enabled: true
  townbank:
    Enabled: true
  nationcreate:
    Enabled: true
  towndelete:
    Enabled: true
  townmayor:
    Enabled: true
  nationbank:
    Enabled: true
# Automatically check for updates and display notifications in game.
# It's recommended to leave this enabled, as I'm constantly improving the plugin.
checkforupdates: true